kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: restore
    image: mcr.microsoft.com/dotnet/sdk:9.0-preview
    commands:
      - dotnet restore
    environment:
      CI: "true"

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0-preview
    commands:
      - dotnet build --no-restore --configuration Release
    environment:
      CI: "true"
    depends_on:
      - restore

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:9.0-preview
    commands:
      - dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
    environment:
      CI: "true"
      NOSWAGGER: "true"
      NODOCUSAURUS: "true"
    depends_on:
      - build

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files: ./coverage/coverage.cobertura.xml
      flags: unittests
      name: codecov-umbrella
      fail_ci_if_error: true
    depends_on:
      - test

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: builds
      template: |
        {{#success build.status}}
          ✅ Build #{{build.number}} succeeded
        {{else}}
          ❌ Build #{{build.number}} failed
        {{/success}}
    depends_on:
      - coverage
    when:
      status: [ success, failure ]