# Utilisation de l'image SDK .NET Windows
FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2019

# Définition du répertoire de travail
WORKDIR /src

# Copie des fichiers du projet
COPY . .

# Commande par défaut
CMD ["dotnet", "build"] 